//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int task_id { get; set; }
        public string task_name { get; set; }
        public string description { get; set; }
        public int user_id { get; set; }
        public int priority_id { get; set; }
        public int status_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
    
        public virtual priority priority { get; set; }
        public virtual status status { get; set; }
        public virtual user user { get; set; }
    }
}
